### ISSUE TITLE
device with multiple interfaces - can't select HID interface or send HID command with open

### ISSUE THREAD

**Issue by QuadCorei8085** [trezor/cython-hidapi#138]
I have a device with multiple interfaces and HID is interface #6.

When opening the device with vendor/product id the read throws an exception.
When opening the device with open_path('') and using of course the correct path to the specific HID interface the read works fine.

API is missing to select an interface for the HID or is it assumed that first interface is the HID commands?

**Comment by flit** [comment]
What OS? Can you provide a complete descriptor dump? (e.g. with `lsusb -v` on Linux.)

Fwiw, [pyocd](https://github.com/pyocd/pyOCD]) uses cython-hidapi for CMSIS-DAPv1 devices that invariably have the HID interface being number 2 or higher, or even multiple HID interfaces. hidapi does sometimes have issues with some devices with multiple HID interfaces on certain OSes (root cause is unclear), but you seem to have a single-HID-interface device.

**Comment by prusnak** [comment]
AFAIK the underlying API written in C does not provide any other option just:
* opening by vendor_id/product_id via [hid_open](https://github.com/libusb/hidapi/blob/59e84ca74fae41a43f8ff3ea96b4f956c79c69b4/hidapi/hidapi.h#L221)
* opening by path via [hid_open_path](https://github.com/libusb/hidapi/blob/59e84ca74fae41a43f8ff3ea96b4f956c79c69b4/hidapi/hidapi.h#L238)

I don't think we can do more here.
